# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msg_img.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'msg_img.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmsg_img.proto\"\x94\x03\n\tMyMessage\x12\x0f\n\x07\x66ield_1\x18\x01 \x01(\x05\x12\x0f\n\x07\x66ield_2\x18\x02 \x01(\x05\x12(\n\nmsg_source\x18\x03 \x01(\x0b\x32\x14.MyMessage.MsgSource\x12\x0f\n\x07\x66ield_4\x18\x04 \x01(\t\x12\x0f\n\x07\x66ield_5\x18\x05 \x01(\t\x1a\x98\x02\n\tMsgSource\x12\x0f\n\x07\x62izflag\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x16\n\x0erisk_file_flag\x18\x03 \x01(\t\x12\x1a\n\x12risk_file_md5_list\x18\x04 \x03(\t\x12+\n\x06\x61lnode\x18\x05 \x01(\x0b\x32\x1b.MyMessage.MsgSource.AlNode\x12\x11\n\timgmsg_pd\x18\x06 \x01(\t\x12\x11\n\tsignature\x18\x07 \x01(\t\x12.\n\x08tmp_node\x18\x08 \x01(\x0b\x32\x1c.MyMessage.MsgSource.TmpNode\x1a\x14\n\x06\x41lNode\x12\n\n\x02\x66r\x18\x01 \x01(\t\x1a\x1f\n\x07TmpNode\x12\x14\n\x0cpublisher_id\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msg_img_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MYMESSAGE']._serialized_start=18
  _globals['_MYMESSAGE']._serialized_end=422
  _globals['_MYMESSAGE_MSGSOURCE']._serialized_start=142
  _globals['_MYMESSAGE_MSGSOURCE']._serialized_end=422
  _globals['_MYMESSAGE_MSGSOURCE_ALNODE']._serialized_start=369
  _globals['_MYMESSAGE_MSGSOURCE_ALNODE']._serialized_end=389
  _globals['_MYMESSAGE_MSGSOURCE_TMPNODE']._serialized_start=391
  _globals['_MYMESSAGE_MSGSOURCE_TMPNODE']._serialized_end=422
# @@protoc_insertion_point(module_scope)
